### ISSUE TITLE
无法连接房间

### ISSUE THREAD

**Issue by Steven52065** [BanqiJane/Bilibili_Danmuji#1]
[DanMuJiInfo.log](https://github.com/BanqiJane/Bilibili_Danmuji/files/4910217/DanMuJiInfo.log)
[DanMuJiInfo_error.log](https://github.com/BanqiJane/Bilibili_Danmuji/files/4910219/DanMuJiInfo_error.log)

java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

另外在电脑上ping b站的弹幕服务的域名是正常的，应该可以排除是dns的原因

**Comment by Steven52065** [comment]
有时连接成功了过几秒就会提示
 2020-07-13 10:08:11,562 DEBUG Websocket:21 -已尝试连接至服务器地址:wss://tx-gz-live-comet-03.chat.bilibili.com:443/sub; 真实房间号为:1546736;主播名字为:洛天依
2020-07-13 10:08:11,563 DEBUG WebSocketProxy:16 -Connectin(连接中)...........................................
2020-07-13 10:08:11,947 DEBUG Websocket:28 -websocket connect open(连接窗口打开)
2020-07-13 10:08:11,949 DEBUG WebSocketProxy:19 -Connecting Success(连接成功)
Exception in thread "Thread-122" java.lang.NullPointerException
        at xyz.acproject.danmuji.thread.core.ParseMessageThread.run(ParseMessageThread.java:223)

然后断开

**Comment by BanqiJane** [comment]
> 有时连接成功了过几秒钟就会提示
> 2020-07-13 10：08：11,562 DEBUG Websocket：21-已尝试连接至服务器地址：wss：//tx-gz-live-comet-03.chat.bilibili。 com：443 / sub; 真实房间号为：1546736;主播名字为：洛天依
> 2020-07-13 10：08：11,563 DEBUG WebSocketProxy：16 -Connectin（连接中）....... ...........................
> 2020-07-13 10：08：11,947 DEBUG Websocket：28 -websocket connect open（连接窗口打开）
> 2020-07-13 10：08：11,949调试WebSocketProxy：19 -Connecting Success（连接成功）
> 线程“ Thread-122” java.lang.NullPointerException
> 在xyz.acproject.danmuji.thread.core.ParseMessageThread.run（ParseMessageThread .java：223）
> 
> 然后收缩

我排除了一下问题  我用压缩软件把它压缩成zip压缩包时 把文件压坏了 没压缩过的是完好的 待会我放出新版本

**Comment by BanqiJane** [comment]
新版本以放出 @Steven52065 [弹幕姬发行版1.0.2修](https://github.com/BanqiJane/Bilibili_Danmuji/releases/tag/1.0.2)

**Comment by Steven52065** [comment]
还有个就是感谢礼物姬设置里的自定义屏蔽的框里，当只添加一种物品时，必须要输入“辣条，” 而不是“辣条” 才能保存（话说这需要再开个问题么？第一次提问，有错误和不礼貌的地方请多包涵）

**Comment by BanqiJane** [comment]
> 还有个就是感谢礼物姬设置里的自定义屏蔽的框里，当只添加一种物品时，必须要输入“辣条，” 而不是“辣条” 才能保存（话说这需要再开个问题么？第一次提问，有错误和不礼貌的地方请多包涵）

两种都可以 辣条  or 辣条， 也行的

**Comment by BanqiJane** [comment]
> 还有个就是感谢礼物姬设置里的自定义屏蔽的框里，当只添加一种物品时，必须要输入“辣条，” 而不是“辣条” 才能保存（话说这需要再开个问题么？第一次提问，有错误和不礼貌的地方请多包涵）

没事 我刚看了一下 现在只有一种的时候必须是 辣条，才行了 这个问题后续会修改的

**Comment by Steven52065** [comment]
好的，麻烦了，感谢您开发的软件
