### ISSUE TITLE
ERROR SpringApplication:837 -Application run failed

### ISSUE THREAD

**Issue by TANGhz17** [BanqiJane/Bilibili_Danmuji#12]
似乎启动不了，是green版
[DanMuJiInfo.log](https://github.com/BanqiJane/Bilibili_Danmuji/files/6249060/DanMuJiInfo.log)
[DanMuJiInfo_error.log](https://github.com/BanqiJane/Bilibili_Danmuji/files/6249061/DanMuJiInfo_error.log)

**Comment by SaKazaKi1999** [comment]
@TANGhz17 可以方便提供一下你的运行环境么  操作系统之类的
