### ISSUE TITLE
登录验证以及小问题

### ISSUE THREAD

**Issue by kroyoo** [BanqiJane/Bilibili_Danmuji#14]
是否可以增加web登录验证？可能部署在本地不需要这个功能，但是我部署在linux上，只要扫码登录之后，从另一台可以直接访问已经登录的账号，是否增加一个登录验证？功能可设置为可选。
昨晚到现在运行快一天，弹幕回复貌似出现错误，重启之后暂未出现
` DEBUG HttpUserData:385 -{"msg":"f","code":0,"message":"f"}
2021-06-09 13:27:44,946 ERROR HttpUserData:386 -发送弹幕失败,原因:f
`
图片
![image](https://user-images.githubusercontent.com/61957721/121353024-a751f200-c8ea-11eb-9275-c275dfc85016.png)

**Comment by kroyoo** [comment]
` java -version
java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode`

Java版本

**Comment by BanqiJane** [comment]
f 是弹幕含房间关键字 是破站原路返回的
![image](https://user-images.githubusercontent.com/44255558/121467912-9093c400-c9ec-11eb-9d7f-127589153445.png)

**Comment by kroyoo** [comment]
> 
> 
> f 是弹幕含房间关键字 是破站原路返回的
> ![image](https://user-images.githubusercontent.com/44255558/121467912-9093c400-c9ec-11eb-9d7f-127589153445.png)

那应该是用户名问题，不过触发关键字之后，后面都发送不了？这是时间封禁发送弹幕还是？因为触发一条之后，后面都是这样的日志，无法确定封禁时间。
关键字的话，B站有没有对应的api？可以预先处理，看来弹幕回复还是用小号稳妥点。

**Comment by BanqiJane** [comment]
是这样的 不是封禁本人发弹幕功能  是要发的弹幕含关键字 发不出去的意思 无任何风险 也无需小号 
你可以在自己或任意直播间（无需直播）打开f12 发一条含关键字的任意弹幕  例如： 404notfound 
然后查看返回的包 或者直接ctrl+R刷新网页 发现弹幕栏本来发的弹幕不见了  那就是因为关键字发不出去的
破站因关键字发不出去的弹幕  前端是没有任何提醒的  从而造成发出去的假象

**Comment by kroyoo** [comment]
> 
> 
> 是这样的 不是封禁本人发弹幕功能 是要发的弹幕含关键字 发不出去的意思 无任何风险 也无需小号
> 你可以在自己或任意直播间（无需直播）打开f12 发一条含关键字的任意弹幕 例如： 404notfound
> 然后查看返回的包 或者直接ctrl+R刷新网页 发现弹幕栏本来发的弹幕不见了 那就是因为关键字发不出去的
> 破站因关键字发不出去的弹幕 前端是没有任何提醒的 从而造成发出去的假象
> 弹幕姬就是把破站原路返回的发弹幕错误信息給打印出来 使其更直观

哦，我明白了，现在也看到完整的弹幕列表了，之后出现关键字才这样，之前停止重启了看不到弹幕姬的正常日志，只有错误的日志，我以为是出现这样就会被封禁。
