### ISSUE TITLE
天气接口怎么使用

### ISSUE THREAD

**Issue by bookmarkies** [BanqiJane/Bilibili_Danmuji#16]
`推荐关键字配置为 （ #||@，天气 ） `
我看文档介绍是有中文括号包含关键字，但是我试了都没有成功，包括改为英文括号、把括号去掉，弹幕回复都是没反应。

版本：2.4.6
java 版本：
java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

![image](https://user-images.githubusercontent.com/76272979/122848022-98414b80-d2bd-11eb-8ab4-98af16200eff.png)

**Comment by BanqiJane** [comment]
天气关键字是  #||@，天气   
没有括号 教程有一定的误导性

**Comment by bookmarkies** [comment]
> 天气关键字是 #||@，天气
> 没有括号 教程文档有一定的误导性

感谢你的回复，已经搞定了，我把有括号那两个删除就可以了，前面我测试把三个都开着，所以没对。
