### ISSUE TITLE
登录方式以及保持登录

### ISSUE THREAD

**Issue by FunGwan8956** [BanqiJane/Bilibili_Danmuji#18]
大佬你好，我看到这个项目只有扫描登录，想问下这种方式的话，多久就需要重新扫描登录？
可以手动导入cookie之类的吗(非专业不懂)。平时在网页端，浏览器登录之后，只要保持使用，登录好像就不会过期，可以使用同一个cookie吗？
我看到项目，好象是保持登录
https://github.com/SK-415/BiliSessdata

**Comment by FunGwan8956** [comment]
大佬，我使用小心心功能，每天还是能够获取24个，是否可以增加一个功能，发送小心心到当前连接的房间。
还有就是签到功能可以设置时间段？或者是随机时间？

**Comment by BanqiJane** [comment]
扫码登录 取至网页端(所以有效时间和网页端一致)，以前是一个多月有效 全网cookie 10个（现在不太清楚） 超出上限过期最旧的一个（修改密码全网过期）；   扫码他不香么 手动输入cookie就硬核，我看了一下那项目 现在想做一些基本操作（不谈骚操作）仅仅要SESSIONDATA这个值是不够的　现在基本都需要bili_jct这个值的(例如最基础的发送弹幕)
关于签到功能自定义修改时间　还有送小心心　我会记录起来　看以后排时间实现（社畜忙，请谅解）

**Comment by FunGwan8956** [comment]
> 
> 
> 扫码登录 取至网页端(所以有效时间和网页端一致)，以前是一个多月有效 全网cookie 10个（现在不太清楚） 超出上限过期最旧的一个（修改密码全网过期）； 扫码他不香么 手动输入cookie就硬核，我看了一下那项目 现在想做一些基本操作（不谈骚操作）仅仅要SESSIONDATA这个值是不够的　现在基本都需要bili_jct这个值的(例如最基础的发送弹幕)
> 关于签到功能自定义修改时间　还有送小心心　这些提议都不错　我会记录起来　看以后排时间实现（社畜忙，请谅解）

感谢大佬回复支持，期待大佬添加功能。导入cookie我是别的发弹幕项目，复制cookie就可以了。

**Comment by bookmarkies** [comment]
> 扫码登录 取至网页端(所以有效时间和网页端一致)，以前是一个多月有效 全网cookie 10个（现在不太清楚） 超出上限过期最旧的一个（修改密码全网过期）； 扫码他不香么 手动输入cookie就硬核，我看了一下那项目 现在想做一些基本操作（不谈骚操作）仅仅要SESSIONDATA这个值是不够的　现在基本都需要bili_jct这个值的(例如最基础的发送弹幕)
> 关于签到功能自定义修改时间　还有送小心心　这些提议都不错　我会记录起来　看以后排时间实现（社畜忙，请谅解）

大佬，cookie是保存在DanmujiProfile吗？那怎么手动转换？希望大佬加一个手动导入cookie的功能，扫码+手动cookie两不误。

**Comment by kroyoo** [comment]
> 
> 
> > 扫码登录 取至网页端(所以有效时间和网页端一致)，以前是一个多月有效 全网cookie 10个（现在不太清楚） 超出上限过期最旧的一个（修改密码全网过期）； 扫码他不香么 手动输入cookie就硬核，我看了一下那项目 现在想做一些基本操作（不谈骚操作）仅仅要SESSIONDATA这个值是不够的　现在基本都需要bili_jct这个值的(例如最基础的发送弹幕)
> > 关于签到功能自定义修改时间　还有送小心心　这些提议都不错　我会记录起来　看以后排时间实现（社畜忙，请谅解）
> 
> 大佬，cookie是保存在DanmujiProfile吗？那怎么手动转换？希望大佬加一个手动导入cookie的功能，扫码+手动cookie两不误。

作者在工具类有[BASE64Encoder.java](https://github.com/BanqiJane/Bilibili_Danmuji/blob/5ffb0f312b480bf87ebe5613e8f63a8e0c389a12/src/main/java/xyz/acproject/danmuji/tools/BASE64Encoder.java)，根据作者的代码，可以看出所需cookies的字段为：`sid` `SESSDATA` `DedeUserID` `bili_jct` `DedeUserID__ckMd5`
如果你有编码基础，可以直接在BASE64Encoder.java进行编解码，已通过编解码测试，没测试可用性，如果手动编码，记得最后保存为
```
ySZL4SBB:@:“编码后字符”
```

**Comment by kroyoo** [comment]
> 
> 
> > > 扫码登录 取至网页端(所以有效时间和网页端一致)，以前是一个多月有效 全网cookie 10个（现在不太清楚） 超出上限过期最旧的一个（修改密码全网过期）； 扫码他不香么 手动输入cookie就硬核，我看了一下那项目 现在想做一些基本操作（不谈骚操作）仅仅要SESSIONDATA这个值是不够的　现在基本都需要bili_jct这个值的(例如最基础的发送弹幕)
> > > 关于签到功能自定义修改时间　还有送小心心　这些提议都不错　我会记录起来　看以后排时间实现（社畜忙，请谅解）
> > 
> > 
> > 大佬，cookie是保存在DanmujiProfile吗？那怎么手动转换？希望大佬加一个手动导入cookie的功能，扫码+手动cookie两不误。
> 
> 作者在工具类有[BASE64Encoder.java](https://github.com/BanqiJane/Bilibili_Danmuji/blob/5ffb0f312b480bf87ebe5613e8f63a8e0c389a12/src/main/java/xyz/acproject/danmuji/tools/BASE64Encoder.java)，根据作者的代码，可以看出所需cookies的字段为：`sid` `SESSDATA` `DedeUserID` `bili_jct` `DedeUserID__ckMd5`
> 如果你有编码基础，可以直接在BASE64Encoder.java进行编解码，已通过编解码测试，没测试可用性，如果手动编码，记得最后保存为
> 
> ```
> ySZL4SBB:@:“编码后字符”
> ```
已实测，正常使用
