### ISSUE TITLE
希望增加一下修改设置网页端口的功能

### ISSUE THREAD

**Issue by Steven52065** [BanqiJane/Bilibili_Danmuji#2]
1.希望增加一下修改设置网页端口的功能，可能会和其他软件的端口冲突
2.自动回复姬设置中修改当前规则除了在pc上可以关闭，其他设备（平板，手机）都没法关闭
3.自动回复姬设置中修改当前规则希望可以加一个满足条件A或条件B 发送内容C的功能，比如   当有人发送了“再见”或者“拜拜”的时候回复“再见”，可以少设置一些回复的项目，修改起来方便一些。
4.自动回复姬希望可以加个黑名单（即使黑名单内的用户发了指定的消息也不会回复，免得有人一直拿回复姬刷屏玩）

奇怪的想法好像有点多...如果不好实现或者比较麻烦的话就算了，感谢作者大大的开发

**Comment by BanqiJane** [comment]
基本完成所有功能
