### ISSUE TITLE
希望增加保存弹幕记录到文件的功能

### ISSUE THREAD

**Issue by Dr-Asm** [BanqiJane/Bilibili_Danmuji#3]

**Comment by xl-jeeter** [comment]
nohup java -jar BiliBili_Danmuji-2.2beta.jar >temp.txt &，试试这个指令，这样子就会在弹幕姬目录下生成一个名为temp的文件，就有文本记录了

**Comment by BanqiJane** [comment]
弹幕不说有本地保存功能么 不知道是不是你说的
![}CWXQ4FH_@QBZAXEL2%G6AA](https://user-images.githubusercontent.com/44255558/94273204-aa809a00-ff76-11ea-8aca-2da995be6441.png)
 @Dr-Asm

**Comment by BanqiJane** [comment]
超时关闭
