### ISSUE TITLE
能否加入识别关键字控制bot功能

### ISSUE THREAD

**Issue by Voosk** [BanqiJane/Bilibili_Danmuji#33]
能否实现设置直播间某个用户为管理员，通过管理员在直播间发送的关键词来实现对bot的控制呢
同时加入字符判断以防止误触发，比如只有带/的指令才会被识别
比如管理员在直播间输入/关闭进入直播间欢迎，bot关闭后返回：以关闭进入直播间欢迎。

**Comment by BanqiJane** [comment]
两个重复的 关闭一个了 以最后一个为准
