### ISSUE TITLE
2.5.0版本 未登录情况下连不上弹幕服务器&登录状态切换偶尔连不上弹幕服务器

### ISSUE THREAD

**Issue by TigerHeadWasp** [BanqiJane/Bilibili_Danmuji#37]
1.未登录情况下 断掉了弹幕处理线程和心跳线程（未登录下连接弹幕服务器 再去登录）
2.（可能）登录状态切换（即退出登录再登录退出登录再登录··············）断掉了弹幕处理线程和心跳线程且未能恢复
![image](https://user-images.githubusercontent.com/65173367/177461744-ee13f460-3600-4622-979c-622dcf459e6d.png)
错误源码位于[https://github.com/BanqiJane/Bilibili_Danmuji/blob/e8fd17b18b76c9c27b3ff4b897c12c70b9010820/src/main/java/xyz/acproject/danmuji/component/impl/ThreadComponentImpl.java#L51](url)

受影响版本：2.5.0
重现：未登录弹幕姬 或者 未登录状态下去连接房间再去登录
规避风险：
1.登录账号后再去连接房间（一定要登录账号）
2.降级版本，使用2.5.0以下版本

**Comment by BanqiJane** [comment]
已修改本地源码 正在测试 计划下版本提供修复

**Comment by BanqiJane** [comment]
2.6.0 fixed
