### ISSUE TITLE
希望支持liunx系统

### ISSUE THREAD

**Issue by Voosk** [BanqiJane/Bilibili_Danmuji#38]
如题

**Comment by BanqiJane** [comment]
只要系统能安装java 都能运行
linux你只需安装java环境 就能运行 
我的弹幕姬就是挂在服务器（系统centos）上运行的
附上java环境包下载地址：
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot

**Comment by wsy741963** [comment]
jar只要搭建jdk环境就能运行啊，java是全平台通用的，这个用的webGUI

**Comment by BanqiJane** [comment]
超时关闭
