### ISSUE TITLE
新版本多久出呢

### ISSUE THREAD

**Issue by Voosk** [BanqiJane/Bilibili_Danmuji#39]
催更

**Comment by BanqiJane** [comment]
最近没什么空 各位久等了 抱歉 希望十月份后能腾出时间来

**Comment by Voosk** [comment]
辛苦了

**Comment by toby1342** [comment]
您好，请问2.6版本在哪儿更新下载呢？

**Comment by BanqiJane** [comment]
> 您好，请问2.6版本在哪儿更新下载呢？

现在还没有 还在测试中 近期会上的

**Comment by toby1342** [comment]
好的，谢谢


| |
假名
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年12月19日 21:02 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [BanqiJane/Bilibili_Danmuji] 新版本多久出呢 (Issue #39) |

您好，请问2.6版本在哪儿更新下载呢？

现在还没有 还在测试中 近期会上的

**Comment by BanqiJane** [comment]
2.6.0 已更新

**Comment by Voosk** [comment]
终于更新了，可惜我单推已经毕业了

**Comment by BanqiJane** [comment]
> 终于更新了，可惜我单推已经毕业了

哈哈 我工作也很少看直播了
