### ISSUE TITLE
2.2版本无法正常使用

### ISSUE THREAD

**Issue by Steven52065** [BanqiJane/Bilibili_Danmuji#4]
[DanMuJiInfo.log](https://github.com/BanqiJane/Bilibili_Danmuji/files/5317642/DanMuJiInfo.log)
[DanMuJiInfo_error.log](https://github.com/BanqiJane/Bilibili_Danmuji/files/5317643/DanMuJiInfo_error.log)

2.1版本是可以使用的，但是时不时会出现掉线的情况，会自动重莲，但基本不成功（好像会进行21次），不知道这个问题在2.2有没有修复

**Comment by BanqiJane** [comment]
提供一下运行环境  系统版本之类的信息

**Comment by Steven52065** [comment]
> 提供一下运行环境 系统版本之类的信息

openjdk 11.0.8 2020-07-14
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1015-raspi aarch64)
设备是树莓派4b

**Comment by BanqiJane** [comment]
好的  我会记录这次错误  那个断线重连已经很久没维护了  下版本将修复    下版本预计几天后放出

**Comment by Steven52065** [comment]
谢谢，祝您国庆中秋快乐

**Comment by BanqiJane** [comment]
同乐！
