### ISSUE TITLE
B站api升级由http升级为https

### ISSUE THREAD

**Issue by zzcabc** [BanqiJane/Bilibili_Danmuji#43]
如图

![9OM({~}$5D_IIC4V0YE@LDL](https://user-images.githubusercontent.com/46120743/203691696-741471a9-9843-4878-8ff8-0e3368cfaefc.jpg)

**Comment by BanqiJane** [comment]
粗略检查了一下 目前没有用到破站开放平台的api  现在用的都是互联网收集交流用的（

**Comment by zzcabc** [comment]
好像确实
