### ISSUE TITLE
現在天氣接口失效了 正尋找代替

### ISSUE THREAD

**Issue by BanqiJane** [BanqiJane/Bilibili_Danmuji#44]
項目一直用的 中國萬年曆的天氣api
好像是10月份的時候失效了
會尋找代餐的
尋找到代餐后會關閉該帖子

**Comment by zzcabc** [comment]
可以试试腾讯天气的api，是抓取的不保证时效

就不pr了，

## 请求通用URL

 `https://wis.qq.com/weather/common`

## 请求参数

|参数|含义|
|---|---|
|source|请求来源，可以填 pc 即来自PC端|
|province|省，比如浙江省|
|city|市，比如杭州|
|country|县区，比如萧山区|
|weather_type|请求的天气类型，这里是最重要的，参数有：observe(观测站数据，例如温度大气压)，forecast_1h（按小时预报），forecast_24h（按天预报），index（指数，比如穿衣指数等），alarm（警告），limit，tips（小提示），rise（日出日落，月出月落），air（空气质量）等 |

## 请求示例
`https://wis.qq.com/weather/common?source=pc&province=%E6%B5%99%E6%B1%9F&city=%E6%9D%AD%E5%B7%9E&country=%E8%90%A7%E5%B1%B1%E5%8C%BA&weather_type=observe|forecast_1h|forecast_24h|index|tips|rise|air`

## 返回参数
太多了，用浏览器打开看吧

```java
final String url = "https://wis.qq.com/weather/common";
StringBuffer sb = new StringBuffer(url);
sb.append("?source=pc&weather_type=observe|forecast_1h|forecast_24h|index|tips|rise|air");
sb.append("&province=").append(province);
sb.append("&city=").append(city);
if (null != country) sb.append("&country=").append(country);
String respData = OkHttp3Utils.getHttp3Utils()
                    .httpGet(sb.toString(), headers, null)
                    .body().string();
JSONObject jsonObject = JSONObject.parseObject(respData);
Integer status = jsonObject.getInteger("status");
if (status.equals(200)) {
    Map<String, List<Weather>> weathers = new HashMap<>();
    JSONObject data = jsonObject.getJSONObject("data");
    JSONObject cold = data.getJSONObject("index").getJSONObject("cold");
    String ganmao = cold.getString("detail");
    JSONObject forecast24h = data.getJSONObject("forecast_24h");
    List<Weather> oldWeathers = new ArrayList<>();
    oldWeathers.add(generateWeather(city, ganmao, forecast24h.getJSONObject("0")));
    weathers.put("old", oldWeathers);
    List<Weather> newWeathers = new ArrayList<>();
    for (int i = 1; i < 8; i++) {
        newWeathers.add(generateWeather(city, ganmao, forecast24h.getJSONObject(String.valueOf(i))));
    }
    weathers.put("new", newWeathers);
} else {
    LOGGER.error("未知错误,原因:" + jsonObject.getString("message"));
}
```
```java
private static Weather generateWeather(String city, String ganmao, JSONObject day) {
        String min_degree = day.getString("min_degree");
        String max_degree = day.getString("max_degree");
        String wendu = min_degree + "℃ - " + max_degree + "℃";
        Weather weather = new Weather();
        weather.setCity(city);
        weather.setGanmao(ganmao);
        weather.setWendu(wendu);
        weather.setFengxiang(day.getString("day_wind_direction"));
        weather.setFengli(day.getString("day_wind_power"));
        return weather;
}
```




## 地市获取

`https://wis.qq.com/city/like`

## 请求参数

|参数|含义|
|---|---|
|source|请求来源，可以填 pc 即来自PC端|
|city|请求的位置，比如杭州，或者萧山区，返回一个模糊匹配结果集|

## 请求示例
`https://wis.qq.com/city/like?source=pc&city=萧山区`
## 返回示例
```json
{"data":{"101210102":"浙江, 杭州, 萧山"},"message":"OK","status":200}
```

```java
String respData = OkHttp3Utils.getHttp3Utils()
                    .httpGet("https://wis.qq.com/city/like?source=pc&city=" + city, headers, null)
                    .body().string();
JSONObject addInfo = JSONObject.parseObject(respData);
JSONObject data = addInfo.getJSONObject("data");
String s = data.toString();
if (s.contains("\",\"")) s = s.split("\",\"")[0];
s = s.split(":")[1];
s = s.replace(" ","");
s = s.replace("\"", "");
s = s.replace("}", "");
String[] split = s.split(",");
if (split.length == 3) {
    province = split[0];
    city = split[1];
    country = split[2];
} else if (split.length == 2) {
    province = split[0];
    city = split[1];
}
```

**Comment by BanqiJane** [comment]
> 可以试试腾讯天气的api，是抓取的不保证时效
> 
> 就不pr了，
> 
> ## 请求通用URL
> `https://wis.qq.com/weather/common`
> 
> ## 请求参数
> 参数	含义
> source	请求来源，可以填 pc 即来自PC端
> province	省，比如浙江省
> city	市，比如杭州
> country	县区，比如萧山区
> weather_type	请求的天气类型，这里是最重要的，参数有：observe(观测站数据，例如温度大气压)，forecast_1h（按小时预报），forecast_24h（按天预报），index（指数，比如穿衣指数等），alarm（警告），limit，tips（小提示），rise（日出日落，月出月落），air（空气质量）等
> ## 请求示例
> `https://wis.qq.com/weather/common?source=pc&province=%E6%B5%99%E6%B1%9F&city=%E6%9D%AD%E5%B7%9E&country=%E8%90%A7%E5%B1%B1%E5%8C%BA&weather_type=observe|forecast_1h|forecast_24h|index|tips|rise|air`
> 
> ## 返回参数
> 太多了，用浏览器打开看吧
> 
> ## Java示例
> ```java
> final String url = "https://wis.qq.com/weather/common";
> StringBuffer sb = new StringBuffer(url);
> sb.append("?source=pc&weather_type=observe|forecast_1h|forecast_24h|index|tips|rise|air");
> sb.append("&province=").append(province);
> sb.append("&city=").append(city);
> if (null != country) sb.append("&country=").append(country);
> String respData = OkHttp3Utils.getHttp3Utils()
>                     .httpGet(sb.toString(), headers, null)
>                     .body().string();
> JSONObject jsonObject = JSONObject.parseObject(respData);
> Integer status = jsonObject.getInteger("status");
> if (status.equals(200)) {
>     Map<String, List<Weather>> weathers = new HashMap<>();
>     JSONObject data = jsonObject.getJSONObject("data");
>     JSONObject cold = data.getJSONObject("index").getJSONObject("cold");
>     String ganmao = cold.getString("detail");
>     JSONObject forecast24h = data.getJSONObject("forecast_24h");
>     List<Weather> oldWeathers = new ArrayList<>();
>     oldWeathers.add(generateWeather(city, ganmao, forecast24h.getJSONObject("0")));
>     weathers.put("old", oldWeathers);
>     List<Weather> newWeathers = new ArrayList<>();
>     for (int i = 1; i < 8; i++) {
>         newWeathers.add(generateWeather(city, ganmao, forecast24h.getJSONObject(String.valueOf(i))));
>     }
>     weathers.put("new", newWeathers);
> } else {
>     LOGGER.error("未知错误,原因:" + jsonObject.getString("message"));
> }
> ```
> 
> ```java
> private static Weather generateWeather(String city, String ganmao, JSONObject day) {
>         String min_degree = day.getString("min_degree");
>         String max_degree = day.getString("max_degree");
>         String wendu = min_degree + "℃ - " + max_degree + "℃";
>         Weather weather = new Weather();
>         weather.setCity(city);
>         weather.setGanmao(ganmao);
>         weather.setWendu(wendu);
>         weather.setFengxiang(day.getString("day_wind_direction"));
>         weather.setFengli(day.getString("day_wind_power"));
>         return weather;
> }
> ```
> 
> ## 地市获取
> `https://wis.qq.com/city/like`
> 
> ## 请求参数
> 参数	含义
> source	请求来源，可以填 pc 即来自PC端
> city	请求的位置，比如杭州，或者萧山区，返回一个模糊匹配结果集
> ## 请求示例
> `https://wis.qq.com/city/like?source=pc&city=萧山区`
> 
> ## 返回示例
> ```json
> {"data":{"101210102":"浙江, 杭州, 萧山"},"message":"OK","status":200}
> ```
> 
> ## Java示例
> ```java
> String respData = OkHttp3Utils.getHttp3Utils()
>                     .httpGet("https://wis.qq.com/city/like?source=pc&city=" + city, headers, null)
>                     .body().string();
> JSONObject addInfo = JSONObject.parseObject(respData);
> JSONObject data = addInfo.getJSONObject("data");
> String s = data.toString();
> if (s.contains("\",\"")) s = s.split("\",\"")[0];
> s = s.split(":")[1];
> s = s.replace(" ","");
> s = s.replace("\"", "");
> s = s.replace("}", "");
> String[] split = s.split(",");
> if (split.length == 3) {
>     province = split[0];
>     city = split[1];
>     country = split[2];
> } else if (split.length == 2) {
>     province = split[0];
>     city = split[1];
> }
> ```

希望能稳定长一段时间吧 能白嫖的天气api越来越少了

**Comment by zzcabc** [comment]
## 百度接口 爬虫展示
```java 
public static void main(String[] args) {
        HttpRequest httpRequest = HttpRequest.get("https://weathernew.pae.baidu.com/weathernew/pc?query=北京天气&srcid=4982");
        httpRequest.header("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36");
        String body = httpRequest.execute().body();
        Document doc = Jsoup.parse(body);
        String data = doc.data();
        String[] split = data.split("\n", 0)[0].split(";window.modifyData = ");
        String tplData = split[0].split("window.tplData = ")[1];
    }


    private static void weather(String tplData){
        JSONObject jsonObject = new JSONObject(tplData);
        JSONObject yesterday15d = jsonObject.getJSONObject("yesterday_15d");
        String date = yesterday15d.getStr("date"); // 昨天
        String weatherDay = yesterday15d.getStr("weather_day"); // 天气状况
        String temperatureDay = yesterday15d.getStr("temperature_day"); // 白天气温
        String temperatureNight = yesterday15d.getStr("temperature_night");// 夜晚气温
        String windDirectionDay = yesterday15d.getStr("wind_direction_day");// 白天风向
        String windDirectionNight = yesterday15d.getStr("wind_direction_night");// 夜晚风向
        String windPowerDay = yesterday15d.getStr("wind_power_day");// 白天风力
        String windPowerNight = yesterday15d.getStr("wind_power_night");// 夜晚风力
        JSONArray jsonArray = jsonObject.getJSONObject("recommend_zhishu").getJSONArray("item");
        String 感冒 = null;
        for (Object o : jsonArray) {
            JSONObject object = new JSONObject(o);
            if ("感冒".equals(object.getStr("item_name"))) {
                感冒 = object.getStr("item_title");
            }
        }
        JSONObject longDayForecast = jsonObject.getJSONObject("long_day_forecast");

        JSONArray info = longDayForecast.getJSONArray("info");
        for (Object o : info) {
            JSONObject object = new JSONObject(o);
            String weatherDay1 = object.getStr("weather_day"); // 天气状况
            String temperatureDay1 = object.getStr("temperature_day"); // 白天气温
            String temperatureNight1 = object.getStr("temperature_night");// 夜晚气温
            String windDirectionDay1 = object.getStr("wind_direction_day");// 白天风向
            String windDirectionNight1 = object.getStr("wind_direction_night");// 夜晚风向
            String windPowerDay1 = object.getStr("wind_power_day");// 白天风力
            String windPowerNight1 = object.getStr("wind_power_night");// 夜晚风力
            String sunriseTime = object.getStr("sunriseTime");// 日出
            String sunsetTime = object.getStr("sunsetTime");// 日落
            String str = object.getJSONObject("humidity").getStr("text"); // 湿度
        }
    }
```

## 依赖
```xml
<dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.11</version>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.15.3</version>
        </dependency>
```

**Comment by BanqiJane** [comment]
感谢提供

**Comment by BanqiJane** [comment]
2.6.1update fixed it
