### ISSUE TITLE
请问感谢姬只想感谢舰长怎么办

### ISSUE THREAD

**Issue by oneole** [BanqiJane/Bilibili_Danmuji#51]
大佬你好！请问只想让感谢姬感谢舰长怎么办。现在页面上都是屏蔽不感谢的，难道要把除舰长外所有礼物都屏蔽吗？谢谢！ 感激不尽！

**Comment by BanqiJane** [comment]
现在并没有白名单 预计下个版本会添加白名单和人员过滤 还有黑名单
所以....

**Comment by oneole** [comment]
好的！

**Comment by BanqiJane** [comment]
2.6.2 fixed it
