### ISSUE TITLE
希望上舰私信姬支持舰长提督总督分别设置感谢内容

### ISSUE THREAD

**Issue by sakurayun** [BanqiJane/Bilibili_Danmuji#52]
希望上舰私信姬支持舰长提督总督分别设置感谢内容及增加关键词：舰长等级（舰长提督总督）%level% 、自定义参数礼物代码%code-1%（舰长）%code-2%（提督）%code-3%（总督）分别提前设置对应等级的礼物代码

例如：
舰长张三上舰
发送：感谢%uName%的%level%,您的礼物代码为 : %code-1%
感谢张三的舰长您的礼物代码为 : Absef3HvsY

**Comment by BanqiJane** [comment]
纳入后续版本考虑

**Comment by BanqiJane** [comment]
2.6.2 try to perfect it
