### ISSUE TITLE
自动创建的目录与文件的权限问题

### ISSUE THREAD

**Issue by slinar** [BanqiJane/Bilibili_Danmuji#54]
### OS
Rocky Linux release 8.7 (Green Obsidian)
### JAVA
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)

## 软件版本
BiliBili_Danmuji-2.6.2beta.jar

## 问题描述
1. 自动创建的目录 Danmuji_log 权限是rwxrwxrwx(777)
2. Danmuji_log 目录中创建的日志文件与 DanmujiProfile 配置文件权限是rw-rw-rw(666)

虽然不是什么大问题，但是这样的权限是不太合适的

## 修正方案
1. 目录的权限通常是rwxr-xr-x(755)
2. 文件的权限通常是rw-r--r--(644)

**Comment by BanqiJane** [comment]
感谢大佬建议

**Comment by BanqiJane** [comment]
2.6.3 fixed
