### ISSUE TITLE
【已解决】更新后无法成功修改配置

### ISSUE THREAD

**Issue by Fengbujue2783** [BanqiJane/Bilibili_Danmuji#58]
如题

**Comment by Fengbujue2783** [comment]
网页看不到配置，但是好像实际上生效了

**Comment by BanqiJane** [comment]
能详细描述过程  和相关截图吗

**Comment by BanqiJane** [comment]
目前已找到问题
1.黑名单屏蔽赠送礼物用户名 写错了 写成了礼物名称....

**Comment by Fengbujue2783** [comment]
因为机器人连入直播间也会被欢迎姬欢迎 尝试填写机器人uid并选择了欢迎 保存并重启网页UI后空格内填写的uid消失 但是在直播间实测似乎没有继续欢迎
尝试使用关键词屏蔽，但这个可能是我没设置好。如果是包含关键词无论位置是直接填入关键词就可以吗，好像会导致机器人停摆（利用自动回复尝试触发无效）
尝试下载配置文件后也没有在里面搜索到上述uid和关键词？
Win10家庭版x64 10.0.19045

**Comment by BanqiJane** [comment]
那奇怪了 如果其他配置不能修改那有可能是文件权限不够了

**Comment by Fengbujue2783** [comment]
![image](https://user-images.githubusercontent.com/130797431/233099665-12f0a655-09f2-4ac5-b9c8-102a3ae116c8.png)
![image](https://user-images.githubusercontent.com/130797431/233099716-34999bdc-d5b8-472e-af51-28c4b48d8161.png)
导出配置文件写入了但是似乎无效
![image](https://user-images.githubusercontent.com/130797431/233100287-13ff35e0-26f7-44c1-9d6a-ffe56988c57f.png)

**Comment by Fengbujue2783** [comment]
补充：似乎有的时候无法成功保存配置
今天在修改自动回复 显示成功保存 但是实际上查日志发现还是原来的样子
