### ISSUE TITLE
弹幕朗读和关闭终端弹幕时间显示的问题

### ISSUE THREAD

**Issue by erdnalfVQF** [BanqiJane/Bilibili_Danmuji#59]
目前在退休的mac上推流顺便看弹幕
windows上的弹幕姬可以接入tts进行朗读，我不清楚大佬的这个项目可不可以也做一个朗读系统，于是用mac自带的旁白对终端进行抓取，然后朗读（Siri的声音好棒www
然后现在有个问题就是收到弹幕的时候会显示收到的时间，导致旁白朗读的时候都会读一遍年月日时分秒（好傻XD
我在设置里找了一下没有找到可以关闭时间显示的设置
所以还想问下在哪里可以关闭终端收到弹幕的时间显示，让人工智障变得不那么智障（指捧读时间Orz

**Comment by erdnalfVQF** [comment]
就是控制台收到弹幕会有收到弹幕的时间，然后Siri就无脑捧读了Orz
e.g. 
2023-04-25 15:35:45:收到弹幕:用户 它说:啦啦啦
然后Siri就会从头读到尾XD
所以想问下前面这一段“2023-04-25 15:35:45:收到弹幕:”或者单独前面的这一段时间可否在哪里删除，救救Siri(੭•̀ᴗ•̀)੭

**Comment by BanqiJane** [comment]
https://github.com/BanqiJane/Bilibili_Danmuji/blob/master/src/main/java/xyz/acproject/danmuji/thread/core/ParseMessageThread.java#L163 位于这一行 基本时间都是stringbuilder append进去的 估计的慢慢去掉

**Comment by erdnalfVQF** [comment]
解决啦 非常感谢！
（Siri的声音太棒了www
