### ISSUE TITLE
登录状态不稳定的问题

### ISSUE THREAD

**Issue by xialei123456** [BanqiJane/Bilibili_Danmuji#63]
大佬好，我在使用海外的机子（racknerd）挂danmuji时，遇到了登录状态不稳定的问题，即danmuji有时会自动退出登录，然后就需要重新登录或者重启来解决，有时一天要重启2-3次，请问可能是由于哪些原因引起的

**Comment by BanqiJane** [comment]
破站的cookie有上限的，现在我太确定上限是多少；总之登录多了，到达上限就会失效之前的cookie，最有可能是这种原因

**Comment by xialei123456** [comment]
> 破站的cookie有上限的，现在我太确定上限是多少；总之登录多了，到达上限就会失效之前的cookie，最有可能是这种原因

原来如此！感谢大佬解答

**Comment by xiaoluo2333** [comment]
原来是这样嘛，我刚刚还发了整整3个邮件
