### ISSUE TITLE
运行一段时间后用户名就变成了首字母加三个

### ISSUE THREAD

**Issue by LastWhisperXX** [BanqiJane/Bilibili_Danmuji#64]
程序跑一段时间后所有的用户名都变成了 第一个字加三个*号，刷新一下就恢复了

群***: 打卡o(￣ヘ￣o＃)
七***: (╯°口°)╯打卡！
忘***: 打卡o(￣ヘ￣o＃)
桃***: ( ｣ﾟДﾟ)｣＜打卡
放***: (〃∀〃)
k***: (╯°口°)╯打卡！
科***: |•'▿'•)✧打卡
![屏幕截图 2023-07-08 014246](https://github.com/BanqiJane/Bilibili_Danmuji/assets/49542507/3b060a92-dc0a-4c9f-9b19-776198452a54)

**Comment by BanqiJane** [comment]
控制台输出 还是网页..

**Comment by LastWhisperXX** [comment]
控制台和网页都是，单独网页版本和代码编译启动版本

**Comment by BanqiJane** [comment]
我目前未发现这个问题，检测一下是不是您的版本代码有修改

**Comment by BanqiJane** [comment]
行，我调试调试这两个包

**Comment by BanqiJane** [comment]
调试了一会，发现破站更新了ws认证的机制 我近期会修复的

**Comment by LastWhisperXX** [comment]
大佬辛苦了

**Comment by BanqiJane** [comment]
已经修复了 但估计这是临时的
破站现在在灰度这项功能 未登录用户因为隐私问题显示*号
