### ISSUE TITLE
连接意外断开，重连卡住的问题

### ISSUE THREAD

**Issue by xialei123456** [BanqiJane/Bilibili_Danmuji#68]
大大好，之前在#63里提到登录状态失效的问题，后面我通过脚本每两个小时重启一次，暂时解决了

但是最近经常出现连接意外断开，重新连接卡住一个小时都不能连上的问题
如下图的info, 18:53分前有几次重连成功了，然后这次重连快一个小时未成功，后面我手动重启后才连接成功
![image](https://github.com/BanqiJane/Bilibili_Danmuji/assets/51240181/ed2db4d1-9e50-4b3e-9198-e7da4adef0a6)

使用的是2.6.41
服务器是海外服务器

**Comment by BanqiJane** [comment]
可能是网络问题 可以试着本地运行一会

**Comment by xialei123456** [comment]
> 可能是网络问题 可以试着本地运行一会

好！我找国内机子测试一下！
