### ISSUE TITLE
无法显示进房

### ISSUE THREAD

**Issue by lanyangyin** [BanqiJane/Bilibili_Danmuji#74]

**Comment by BanqiJane** [comment]
请问是未登录弹幕姬的情况下吗

**Comment by lanyangyin** [comment]
是的，但是似乎和登录状态无关，控制台有输出进房信息，但是网web并没有显示出来[测试的图片](https://1drv.ms/i/s!AvygrNSoNOXL3V6ThV9zclljGYxj?e=sYtXeu)

**Comment by lanyangyin** [comment]
似乎和登陆状态无关，控制台有进房消息，但是web没有，没登陆像这个[图片](https://1drv.ms/i/s!AvygrNSoNOXL3WAReqGrBpYejinH?e=TcjoPU)一样，登陆后是[这样](https://1drv.ms/i/s!AvygrNSoNOXL3WGF6T7qTIYpPcHd?e=ja1pE8)。

**Comment by BanqiJane** [comment]
了解，这个问题预估下版本解决，是没有转发进入直播间的包给操作界面

**Comment by BanqiJane** [comment]
2.6.5 fixed it
