### ISSUE TITLE
 绿色版的天气参数怎么没反应

### ISSUE THREAD

**Issue by jasonwang1111** [BanqiJane/Bilibili_Danmuji#75]
![屏幕截图 2023-10-31 233451](https://github.com/BanqiJane/Bilibili_Danmuji/assets/120768050/64d583b5-3eec-433d-8f9b-8b20f3629041)
发送一模一样的”#广州天气“也没反应

**Comment by BanqiJane** [comment]
是天气服务器问题 已经修复完毕

**Comment by BanqiJane** [comment]
已确认修复（热修复）
