### ISSUE TITLE
添加自定义回复时存在bug

### ISSUE THREAD

**Issue by zzy563** [BanqiJane/Bilibili_Danmuji#76]
添加新规则时，点击右上角的X保存时，会把当前的规则给删除，新建多个规则，编辑其中某一条规则可以避免触发该bug，但是有些麻烦，希望修正一下。

**Comment by zzy563** [comment]
编辑完后点击X会有一定概率删除当前编辑的规则，好像有自动删除空规则的功能，猜测和该功能有关系。

**Comment by BanqiJane** [comment]
版本是最新版吗

**Comment by BanqiJane** [comment]
复现到了 是不是开启了自动保存 才会触发

**Comment by BanqiJane** [comment]
跟机制有关 是这样的：
回复词不能为空 如果空 就不能保存的

**Comment by BanqiJane** [comment]
2.7.0.0 fixed it
