### ISSUE TITLE
导入设置好像会漏掉自动回复部分

### ISSUE THREAD

**Issue by SamZebrado** [BanqiJane/Bilibili_Danmuji#80]
我用GPT多搞了些配置
其他的都能导入，
但是自动回复的规则没有导进去的样子
[GPTenhancedSet2.json](https://github.com/BanqiJane/Bilibili_Danmuji/files/14086605/GPTenhancedSet2.json)
求测试，谢谢您！

**Comment by SamZebrado** [comment]
已经解决了，重启程序似乎就可以了（电脑更新之后发现自动回复的设置已经导入了～）

**Comment by BanqiJane** [comment]
我测试一下为什么不能实时导入

**Comment by xiaoluo2333** [comment]
导入完别点击保存，会自动保存的，直接刷新页面就可以了

**Comment by xiaoluo2333** [comment]
导入完别点击保存，会自动保存的，直接刷新页面就可以了

导入完自动刷新页面后续可以加进去嘛
