### ISSUE TITLE
[通用设置]-[弹幕记录]-勾选保存无效

### ISSUE THREAD

**Issue by chadian20** [BanqiJane/Bilibili_Danmuji#81]
### 使用版本：danmuji-green( window64绿色版本，不用配置安装java环境)
1.[通用设置]-[弹幕记录]-勾选保存无效。
2.天气接口和APEX英雄数据接口无效。

**Comment by BanqiJane** [comment]
1 测试没什么问题  需要提交额外信息 例如弹幕姬运行环境操作系统等信息
2 天气接口和apex接口是因为弹幕姬服务器redis炸了 现在已经恢复
