### ISSUE TITLE
cookie大概3天左右失效

### ISSUE THREAD

**Issue by chadian20** [BanqiJane/Bilibili_Danmuji#83]
1.每3天需要扫码一次，有能够持久一点的办法吗？
2.跟直播间发送弹幕数量有关系？发的多所以cookie时效很短？

**Comment by BanqiJane** [comment]
没有 我挂的几个月都没有失效，建议不要经常在很多设备登录或者退出登录，因为破站的cookie有上限的，例如上限3个的话，就会使其他失效

**Comment by chadian20** [comment]
测试了，大概2年前注册的老号很久不会过期，但最近1年和1个月注册的，3天一掉。

**Comment by BanqiJane** [comment]
感谢测试 那么说破站调整了新号的cookie过期时间
