### ISSUE TITLE
弹幕保存本地问题

### ISSUE THREAD

**Issue by fyq258** [BanqiJane/Bilibili_Danmuji#88]
我在网页打开弹幕保存本地之后，刷新一下网页，它自己取消了，不过弹幕文件还是有保存的，从3月26日开始的，之前是好的。版本为2.7.0.1绿色版，但是非绿色版也有这个问题
这是打开选项：
![Screenshot_2024-03-26-10-59-08-677](https://github.com/BanqiJane/Bilibili_Danmuji/assets/140613280/7a4bd730-fe5f-4f17-aea1-ad90ebcde5fb)
这是刷新之后：
![Screenshot_2024-03-26-10-59-27-619](https://github.com/BanqiJane/Bilibili_Danmuji/assets/140613280/47b93c64-271c-452d-ad99-619d56abb070)

**Comment by fyq258** [comment]
破案了

**Comment by BanqiJane** [comment]
是按钮显示问题，显示不出他是否开启现在打包版都有这个问题 ，源码已经修复了 等之后版本一起打包

**Comment by fyq258** [comment]
ok 谢谢您
