### ISSUE TITLE
弹幕姬的自动回复里头的%LIVETIME% 不是北京时间

### ISSUE THREAD

**Issue by Cecilia-Zhong** [BanqiJane/Bilibili_Danmuji#9]
弹幕姬的自动回复里头的%LIVETIME% 不是北京时间， 和实际相差了半个小时。

**Comment by SaKazaKi1999** [comment]
%LIVETIME% 获取的是当前房间持续直播了多少时间  %TIME%是获取本地系统时间 请确定参数
