### ISSUE TITLE
欢迎功能有问题

### ISSUE THREAD

**Issue by PullAndRun** [BanqiJane/Bilibili_Danmuji#90]
欢迎功能的仅勋章选项无效，全部人都会欢迎，不戴牌子的都会欢迎。

**Comment by BanqiJane** [comment]
有更多信息和截图吗 ，本地调试未能复现问题（接口有返回勋章信息的），感觉有可能像是观众的勋章未点亮 或者未戴上

**Comment by PullAndRun** [comment]
> 有更多信息和截图吗 ，本地调试未能复现问题（接口有返回勋章信息的），感觉有可能像是观众的勋章未点亮 或者未戴上

谢谢！可能是我这边的问题。我再继续观察！
